V0.1.0 - Stardardize Object Definition
mapikit/meta-function-helper pull request #1
Opened 2021-06-02 16:14 UTC by flgmjr

2021-06-02 21:49 UTC, homemmakako commented on src/error-codes.ts
> +  V32 = "V32 - Property \"required\" must be a string",
Typo: "V32 - Property \"required\" must be a ~string~ boolean"

2021-06-02 22:12 UTC, homemmakako requested changes
`customTypes` should be optional instead of a mandatory, possibly empty array

2021-06-03 22:31 UTC, flgmjr commented
@homemmakako  Fixed the comments, please Review again.

2021-06-04 01:47 UTC, homemmakako approved these changes

2021-06-04 01:49 UTC, merged